# Generated by Django 5.2.1 on 2025-05-28 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("photo", models.ImageField(upload_to="vehicules/")),
                (
                    "marque",
                    models.CharField(
                        choices=[
                            ("DS Automobiles", "DS Automobiles"),
                            ("BMW", "BMW"),
                            ("Mercedes Benz", "Mercedes Benz"),
                            ("Land Rover", "Land Rover"),
                            ("Opel", "Opel"),
                            ("Citroën", "Citroën"),
                            ("Lamborghini", "Lamborghini"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "modele",
                    models.CharField(
                        choices=[
                            ("DS 7 Crossback E-Tense", "DS 7 Crossback E-Tense"),
                            ("DS 3", "DS 3"),
                            ("Grand lander", " Grand lander"),
                            ("Crossland", "Crossland"),
                            ("XM", "XM"),
                            ("Range Rover Sport", "Range Rover Sport"),
                            ("Range Rover Velar", "Range Rover Velar"),
                            ("Classe GT", "Classe GT"),
                            ("Classe GLE 53", "Classe GLE 53"),
                            ("Classe S63", "Classe S63"),
                            ("URUS", "URUS"),
                            ("C4X Ë série", "C4X Ë série"),
                            ("Aventador SV Roadster", "Aventador SV Roadster"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "carburant",
                    models.CharField(
                        choices=[
                            ("Essence", "Essence"),
                            ("Hybride", "Hybride"),
                            ("Diesel", "Diesel"),
                            ("Electric", "Electric"),
                            ("Gasoil", "Gasoil"),
                        ],
                        default="Essence",
                        max_length=50,
                    ),
                ),
                ("kilometrage", models.PositiveIntegerField()),
                ("annee", models.PositiveIntegerField()),
                (
                    "transmission",
                    models.CharField(
                        choices=[
                            ("Manuelle", "Manuelle"),
                            ("Automatique", "Automatique"),
                        ],
                        max_length=50,
                    ),
                ),
                ("prix", models.PositiveIntegerField()),
                ("description", models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="VehicleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="vehicules/gallery/")),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="vehicules.vehicle",
                    ),
                ),
            ],
        ),
    ]
